### ISSUE TITLE
What was the GPU that you used to train your model??

### ISSUE THREAD

**Issue by kshitijchandna** [keunwoochoi/music-auto_tagging-keras#27]
I am very new to this but which GPU did you use while training it on MTT?? My kernal dies constantly on Tensorflow-GPU with Nvidia 960m.

**Comment by keunwoochoi** [comment]
I used Titan but it shouldn't be about GPU. Could be about backend - theano and tensorflow. Could you check how's it working if you use compact_cnn folder in the tepo with keras 1.2?

**Comment by kshitijchandna** [comment]
You were right it was about the backend. After some minor changes to the code,CRNN worked perfectly with Keras 2 with tensorflow as backend.

**Comment by keunwoochoi** [comment]
Great. If you're gonna learn your model from scratch, it should be fine. 

If you wanna load and use the weights, please note that...

Due to the different BN implementations in keras version <= 1.0.6, and keras <= 1.2.2, and keras 2.x (whoa), the prediction would probably be weird. Compact_CNN is also in the case, so you probably need to use virtualenv and install some old versions. Sorry for this ;)
